use_frameworks!

platform :ios, '8.0'

target 'BadgeView_Example' do
  pod 'BadgeView', :path => '../'

  target 'BadgeView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
